### ISSUE TITLE
Issue in PHP version 7.x

### ISSUE THREAD

**Issue by kaushikindianic** [crodas/Notoj#6]
Fatal error: Cannot use Notoj\Object as Object because 'Object' is a special class name in vendor/crodas/notoj/lib/Notoj/Annotation/Common.php on line 39

**Comment by crodas** [comment]
@kaushikindianic Thank you for using Notoj.

I fixed already this issue and I created a new release(`1.6.1`). Just run `composer update` and if it does not get the latest version just update the version in your composer.json to `^1.6`.

I renamed to `TObject` instead of your naming and I updated everywhere, it was referenced in many places.

Again, thank you for contributing.

**Comment by crodas** [comment]
Just for the record, e82c216fc8666011e8962710259f202330e4c33c is the commit that fixed this issue.
